name: "dojo-toolchain"
description: "Install Dojo"
author: "Dojo"
branding:
  color: "gray-dark"
  icon: "play-circle"

inputs:
  version:
    default: "nightly"
    description: |
      Dojo version.

      This version number has to match a released version of Dojo.
      The default value is `nightly`, which will pull the latest nightly build.
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
